### ISSUE TITLE
Yams prerequisites - Not fixed

### ISSUE THREAD

**Issue by Soulfulant12** [richardbenson/YAMS#170]
I have recently install yams however when I start the setup everything is fine until i got to the requirements page I completed the java ones. 

The Mine-craft requirements I found a video tutorial however it did not work I tryed to re install
the Yams client but that didn't work .

My OS is Windows 8.1 64-bit

I will check back once everyday 

any help will be appreciated 

And I hope you will continue Yams I don't mind how slow you are.

**Comment by oldmud0** [comment]
What OS do you have? If you move the .minecraft folder to the All Users' AppData/Roaming folder, does it have any effect?

**Comment by Soulfulant12** [comment]
Windows 8.1 64-bit is my OS                

And my .minecraft folder is already is the roaming folder 

any more suggestions

**Comment by oldmud0** [comment]
Did you fix it?

**Comment by Soulfulant12** [comment]
no I didnt sadly

**Comment by STiCory** [comment]
You don't need the client for most installs, I have the client on my computer as I host the server on my local machine and play on it as well, but YAMS doesn't show it installed, no big deal as I don't use those features of YAMS.

**Comment by Soulfulant12** [comment]
Thanks
