### ISSUE TITLE
Mine craft Yams prerequisites 

### ISSUE THREAD

**Issue by Soulfulant12** [richardbenson/YAMS#171]
I have recently install yams however when I start the setup everything is fine until i got to the requirements page I completed the java ones.

The Mine-craft requirements I found a video tutorial however it did not work I tryed to re install
the Yams client but that didn't work .

Windows 8.1 64-bit is my OS

And my .minecraft folder is already is the roaming folder

any help will be appreciated

And I hope you will continue Yams I don't mind how slow you are.

**Comment by Soulfulant12** [comment]
Any suggestions will be welcome

**Comment by STiCory** [comment]
duplicate of #170
