### ISSUE TITLE
Yams Updater will not run

### ISSUE THREAD

**Issue by zbturtle** [richardbenson/YAMS#174]
This is all yams updater tells me no mater how hard i try to fix it so i wont have to bother you guys but i just cant find it
![yams-updater exe unhandledexception](https://cloud.githubusercontent.com/assets/11141080/6452626/da7cb902-c0eb-11e4-89ab-044527ae331a.png)
The development team was automatically notified of this problem. If you need immediate assistance, contact .

The following information about the error was automatically captured: 

 • a screenshot was taken of the desktop at:
   C:\Program Files (x86)\YAMS\YAMS-Updater.exe.UnhandledException.png
 • details were written to a text log at:
   C:\Program Files (x86)\YAMS\YAMS-Updater.exe.UnhandledExceptionLog.txt
 • attempted to send an email to: 
   The key <UnhandledExceptionManager/EmailTo> is not present in the <appSettings> section of .config file

Detailed error information follows:

(Inner Exception)
Date and Time:         3/2/2015 2:52:14 PM
Machine Name:          ZACHSCOMPUTER
IP Address:            192.168.1.4
Current User:          ZACHSCOMPUTER\zachary

Application Domain:    YAMS-Updater.exe
Assembly Codebase:     file:///C:/Program Files (x86)/YAMS/YAMS-Updater.exe
Assembly Full Name:    YAMS-Updater, Version=0.9.0.0, Culture=neutral, PublicKeyToken=null
Assembly Version:      0.9.0.0
Assembly Build Date:   2/7/2015 8:01:34 PM

Exception Source:      SQL Server Compact ADO.NET Data Provider
Exception Type:        System.Data.SqlServerCe.SqlCeException
Exception Message:     The database file is larger than the configured maximum database size. This setting takes effect on the first concurrent database connection only. [ Required Max Database Size (in MB; 0 if unknown) = 2049 ]
Exception Target Site: ProcessResults

---- Stack Trace ----
   System.Data.SqlServerCe.SqlCeCommand.ProcessResults(hr As Int32)
       YAMS-Updater.exe: N 00045
   System.Data.SqlServerCe.SqlCeCommand.ExecuteCommandText(pCursor As IntPtr&, isBaseTableCursor As Boolean&)
       YAMS-Updater.exe: N 00517
   System.Data.SqlServerCe.SqlCeCommand.ExecuteCommand(behavior As CommandBehavior, method As String, options As ResultSetOptions)
       YAMS-Updater.exe: N 00490
   System.Data.SqlServerCe.SqlCeCommand.ExecuteNonQuery()
       YAMS-Updater.exe: N 00044
   YAMS.Database.AddLog(strMessage As String, strSource As String, strLevel As String, bolSendToAdmin As Boolean, intServerID As Int32)
       YAMS-Updater.exe: N 00638

(Outer Exception)
Date and Time:         3/2/2015 2:52:14 PM
Machine Name:          ZACHSCOMPUTER
IP Address:            192.168.1.4
Current User:          ZACHSCOMPUTER\zachary

Application Domain:    YAMS-Updater.exe
Assembly Codebase:     file:///C:/Program Files (x86)/YAMS/YAMS-Updater.exe
Assembly Full Name:    YAMS-Updater, Version=0.9.0.0, Culture=neutral, PublicKeyToken=null
Assembly Version:      0.9.0.0
Assembly Build Date:   2/7/2015 8:01:34 PM

Exception Source:      YAMS-Library
Exception Type:        System.Exception
Exception Message:     The database file is larger than the configured maximum database size. This setting takes effect on the first concurrent database connection only. [ Required Max Database Size (in MB; 0 if unknown) = 2049 ]
Exception Target Site: AddLog

---- Stack Trace ----
   YAMS.Database.AddLog(strMessage As String, strSource As String, strLevel As String, bolSendToAdmin As Boolean, intServerID As Int32)
       YAMS-Updater.exe: N 00812
   YAMS_Updater.Program.Main(args As String[])
       YAMS-Updater.exe: N 00491

Yams-Updater is failing and it was working yesterday until i restarted my computer and i didnt change anything in it i even tried restarting my computer another 13 times!

**Comment by oldmud0** [comment]
Hmm, might have been caused by an update to SQL Server Compact Edition. Somebody needs to update the connection string and add `Max Database Size=2050` to it.

**Comment by zbturtle** [comment]
How do I do that sorry I'm only 11.

**Comment by richardbenson** [comment]
Run the Service controller from the start menu, there's a button in there that says "truncate logs", this will clear out old data and allow you to run YAMS again.

**Comment by zbturtle** [comment]
dont worry i gave up on yams

**Comment by zbturtle** [comment]
took you so long
