### ISSUE TITLE
Fix for client installation

### ISSUE THREAD

**Issue by ntindle** [richardbenson/YAMS#176]
I don't know much code especially C# but I know what is wrong. When installing I cannot turn all the check marks green because it cannot find my minecraft install because it is looking in the wrong place. Any version of minecraft past 1.5.2 no longer has a `bin` directory. Instead every version is kept inside `.minecraft\versions\`. Under the versions directory each version has its own folder with the `.jar` of the same name as the folder being inside it. All that needs changed is 
`Source/YAMS-Library/Functions/Util.cs` to look for the most current version of minecraft. 

Example directories: 
`C:\Users\[User]\AppData\Roaming\.minecraft\versions\1.8.3\1.8.3.jar`
`C:\Users\Nick\AppData\Roaming\.minecraft\versions\1.8.1\1.8.1.jar` 
 et cetera

**Comment by oldmud0** [comment]
I should make a pull request for this. Remind me if I don't reply to this in a week.

**Comment by oldmud0** [comment]
Unfortunately VS 2013 doesn't support Windows Installer anymore. Bummer..

**Comment by ntindle** [comment]
I'm reminding you

**Comment by LeadMagnet** [comment]
ummm....yeah it does!

https://visualstudiogallery.msdn.microsoft.com/9abe329c-9bba-44a1-be59-0fbf6151054d

**Comment by oldmud0** [comment]
Oh okay. Well I wonder who's going to accept my pull request when I create it.

**Comment by oldmud0** [comment]
Here's the new MSI:
https://dl.dropboxusercontent.com/s/v3u57fzd4scwjqq/YAMS-Setup.msi?dl=0

**Comment by richardbenson** [comment]
Oh wow, only just seen this and that you've compiled!

I don't usually rebuild the MSI anyway, as it pull down the latest files on run, so just need to compile the DLLs and EXEs if they've changed.  Gimme a bit and I'll check the proposed changes.
